steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cix-tech-mart-api:$COMMIT_SHA', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cix-tech-mart-api:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cix-tech-mart-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cix-tech-mart-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1	'
images:
  - 'gcr.io/$PROJECT_ID/cix-tech-mart-api:$COMMIT_SHA'